CREATE TABLE BANCO (
    ID       NUMBER(10, 0)     NOT NULL,
    NOME     VARCHAR(255)      NOT NULL,
    CONSTRAINT CONTA_PK
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE (
    ID        NUMBER(10, 0)      NOT NULL,
    NOME      VARCHAR(255)       NOT NULL,
    CONSTRAINT CONTA_PK
    PRIMARY KEY (ID)
);

CREATE TABLE CONTA (
    id INT PRIMARY KEY AUTO_INCREMENT,
    TIPOCONTA VARCHAR(255) NOT NULL,
    NUMERO INT NOT NULL,
    AGENCIA INT NOT NULL,
    SALDO DOUBLE NOT NULL,
    DATACADASTRO DATETIME,
    CLIENTE_ID INT,
    BANCO_ID INT,
    FOREIGN KEY (CLIENTE_ID) REFERENCES cliente(id),
    FOREIGN KEY (BANCO_ID) REFERENCES banco(id)
);

CREATE SEQUENCE SEQ_BANCO
    START WITH
        1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_CONTA
    START WITH
        1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_CLIENTE
    START WITH
        1 INCREMENT BY 1;