spring:
  datasource:
    url: jdbc:h2:file:~/banco
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  flyway:
      url: jdbc:h2:file:~/banco
      user: sa
      password: sa
      enabled: true
      locations: classpath:db/migration
server:
  port: 8080


